### ISSUE TITLE
Illegal?

### ISSUE THREAD

**Issue by Malaska678** [SnowFuryHQ/boardwalk#1]
It contain OracleJDK which is only free if use personally. Boardwalk 1.9 contains oracle JDK. Sooooooooo.......

**Comment by SnowNF** [comment]
Did you mean change OracleJDK to OpenJDK?

**Comment by Malaska678** [comment]
U decide. Keep it or change it.

**Comment by Malaska678** [comment]
Oracle JDK is not free for non personal use.

**Comment by SnowNF** [comment]
Thanks.
I'll change it to OpenJDK. :)

**Comment by Malaska678** [comment]
:))

**Comment by Malaska678** [comment]
What about glibc used by boardwalk 1.9? It need modification

**Comment by Malaska678** [comment]
https://github.com/BoardwalkApp/boardwalk19-glibc

**Comment by SnowNF** [comment]
This project is under GPLv3..
It's no need to modify.  :)

**Comment by Malaska678** [comment]
Noice

**Comment by Malaska678** [comment]
Thanks. I will test boardwalk 1.9 openjdk. The change might be bad if u look at performance but now you dont need to pay some money.

**Comment by Malaska678** [comment]
Gonna close this.......

**Comment by Malaska678** [comment]
Also sorry

**Comment by Malaska678** [comment]
@ SnowNF If u really like, u can use the glibc so u can use openj9 without porting it to android.

**Comment by Malaska678** [comment]
Open j9 is better than openjdk according to some people

**Comment by SnowNF** [comment]
B...ut Openj9 doesn't have arm32.....

**Comment by Malaska678** [comment]
True. Also its useless becoz aot.

**Comment by Malaska678** [comment]
So forgot that

**Comment by Malaska678** [comment]
Oops they have both JIT and AOT.

**Comment by Malaska678** [comment]
@SnowNF U can use un modified open jdk.
